In [1]:
import pandas as pd

In [2]:
import os
os.getcwd()

'z:\\project files\\Severe Injury Dashboard'

In [3]:
df = pd.read_csv('logistics_companies_add_columns.csv')

In [4]:
df.head(5)

,ID,UPA,EventDate,Employer,Address1,Address2,city,state,Zip,Latitude,...,Unnamed: 25,Source,sourceTitle,Secondary_Source,Secondary_Source_Title,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31
0,20251111336,2365642,11/13/2025,Ruan Transportation Management Systems,Flowers Bakery,6000 NE Loop 410,SAN ANTONIO,TEXAS,78218,29.46,...,"Falls, slips, trips",4741,"Vehicle trailers, trailing units",660,"Ground, travel, and support surfaces unspeci...",NaN,NaN,NaN,Eternity Express Inc.,NaN
1,20251111151,2365320,11/10/2025,Wesco Distribution,5935 Eisenhauer Rd,Building 100,SAN ANTONIO,TEXAS,78218,29.50,...,Transportation incidents,8621,"Forklift, order picker, platform truck powered",6339,Structural barriers n.e.c.,NaN,NaN,NaN,Clean Infrastructure LLC,NaN
2,20251111068,2370023,11/6/2025,Mata Trucking,FM 917,NaN,JOSHUA,TEXAS,76058,32.46,...,"Falls, slips, trips",4741,"Vehicle trailers, trailing units",660,"Ground, travel, and support surfaces unspeci...",NaN,NaN,NaN,Greg Rose Home Services,NaN
3,20251110889,2366721,11/1/2025,88 Trucking,12250 Lake June Rd Ste 110,NaN,BALCH SPRINGS,TEXAS,75180,32.73,...,"Falls, slips, trips",8432,"Straight trucks, box trucks",990,"Source, secondary source unspecified",NaN,NaN,NaN,Lone Wolf Trucking Inc.,NaN
4,20251010788,2365472,10/29/2025,Southeastern Freight Lines,9199 W. Hardy Road,NaN,HOUSTON,TEXAS,77022,29.84,...,Contact with objects and equipment,4749,Vehicle and machine attachments n.e.c.,4741,"Vehicle trailers, trailing units",NaN,NaN,NaN,Day & Zimmermann Lone Star LLC,NaN

In [5]:
df.columns.tolist()

['ID',
 'UPA',
 'EventDate',
 'Employer',
 'Address1',
 'Address2',
 'city',
 'state',
 'Zip',
 'Latitude',
 'Longitude',
 'Primary_NAICS',
 'Hospitalized',
 'Amputation',
 'Loss_Of_Eye',
 'Inspection',
 'FinalNarrative',
 'Types_of_accidents',
 'Reason',
 'Nature',
 'NatureTitle',
 'Part_of_Body',
 'Part_of_Body_Title',
 'Event',
 'EventTitle',
 'Unnamed: 25',
 'Source',
 'sourceTitle',
 'Secondary_Source',
 'Secondary_Source_Title',
 'Unnamed: 27',
 'Unnamed: 28',
 'Unnamed: 29',
 'Unnamed: 30',
 'Unnamed: 31']

In [6]:
df[["EventTitle", "Types_of_accidents", "Reason"]].head(10)

,EventTitle,Types_of_accidents,Reason
0,Other fall to lower level 6 to 30 feet,"Falls, slips, trips",Insufficient detail in narrative
1,"Collision with stationary object, nonroadway",Transportation incidents,Insufficient detail in narrative
2,Other fall to lower level 6 to 30 feet,"Falls, slips, trips",Inadequate safety procedures
3,Other fall to lower level less than 6 feet,"Falls, slips, trips",Insufficient detail in narrative
4,Injured by object pushed or pulled by person,Contact with objects and equipment,Inadequate safety procedures
5,Fall on same level n.e.c.,"Falls, slips, trips",Insufficient detail in narrative
6,"Caught, entangled in running powered equipmen...",Contact with objects and equipment,Missing machine guards
7,Fall on same level and catch oneself,"Falls, slips, trips",Inadequate safety procedures
8,Other fall to lower level less than 6 feet,"Falls, slips, trips",Poor equipment maintenance
9,"Slip, trip, stumble while stepping between le...","Falls, slips, trips",Insufficient detail in narrative

In [7]:
df["Types_of_accidents"].value_counts(dropna=False)

Types_of_accidents
Contact with objects and equipment                   191
Falls, slips, trips                                  150
Transportation incidents                              90
Exposure to harmful substances or environments        62
Overexertion and bodily reaction                      11
Violence and other injuries by persons or animals      7
Fires and explosions                                   6
Name: count, dtype: int64

In [8]:
df["Reason"].value_counts(dropna=False)

Reason
Inadequate safety procedures        216
Insufficient detail in narrative    114
Unsafe workplace layout              82
Poor hazard identification           62
Poor equipment maintenance           18
Inadequate safety training           13
Missing machine guards               10
Failure to correct known hazards      2
Name: count, dtype: int64

In [9]:
df.shape

(517, 35)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 35 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      517 non-null    int64
 1   UPA                     517 non-null    int64
 2   EventDate               517 non-null    str
 3   Employer                517 non-null    str
 4   Address1                516 non-null    str
 5   Address2                34 non-null     str
 6   city                    517 non-null    str
 7   state                   517 non-null    str
 8   Zip                     517 non-null    int64
 9   Latitude                516 non-null    float64
 10  Longitude               516 non-null    float64
 11  Primary_NAICS           517 non-null    int64
 12  Hospitalized            517 non-null    int64
 13  Amputation              517 non-null    int64
 14  Loss_Of_Eye             517 non-null    int64
 15  Inspection              97 non-null     float64
 16  FinalNarrative          517 non-null    str
 17  Types_of_accidents      517 non-null    str
 18  Reason                  517 non-null    str
 19  Nature                  517 non-null    str
 20  NatureTitle             517 non-null    str
 21  Part_of_Body            517 non-null    str
 22  Part_of_Body_Title      517 non-null    str
 23  Event                   517 non-null    str
 24  EventTitle              517 non-null    str
 25  Unnamed: 25             517 non-null    str
 26  Source                  517 non-null    str
 27  sourceTitle             517 non-null    str
 28  Secondary_Source        325 non-null    str
 29  Secondary_Source_Title  325 non-null    str
 30  Unnamed: 27             2 non-null      str
 31  Unnamed: 28             1 non-null      str
 32  Unnamed: 29             0 non-null      float64
 33  Unnamed: 30             68 non-null     str
 34  Unnamed: 31             0 non-null      float64
dtypes: float64(5), int64(7), str(23)
memory usage: 397.9 KB

In [11]:
missing_counts = df.isna().sum()
missing_counts[missing_counts > 0]

Address1                    1
Address2                  483
Latitude                    1
Longitude                   1
Inspection                420
Secondary_Source          192
Secondary_Source_Title    192
Unnamed: 27               515
Unnamed: 28               516
Unnamed: 29               517
Unnamed: 30               449
Unnamed: 31               517
dtype: int64

In [12]:
unamed_columns = [
    "Unnamed: 27", "Unnamed: 28", "Unnamed: 29",
    "Unnamed: 30", "Unnamed: 31"
]

In [13]:
df[unamed_columns].dropna(how="all").head(10)

,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31
0,NaN,NaN,NaN,Eternity Express Inc.,NaN
1,NaN,NaN,NaN,Clean Infrastructure LLC,NaN
2,NaN,NaN,NaN,Greg Rose Home Services,NaN
3,NaN,NaN,NaN,Lone Wolf Trucking Inc.,NaN
4,NaN,NaN,NaN,Day & Zimmermann Lone Star LLC,NaN
5,NaN,NaN,NaN,Fortune Foods Texas Inc.,NaN
6,NaN,NaN,NaN,"Lumin8 Transportation Technologies, LLC",NaN
7,NaN,NaN,NaN,FC Drywall,NaN
8,NaN,NaN,NaN,"Village Plumbing, Air & Electric",NaN
9,NaN,NaN,NaN,Upstage Center Acquisitions,NaN

In [14]:
df[unamed_columns].notna().sum()

Unnamed: 27     2
Unnamed: 28     1
Unnamed: 29     0
Unnamed: 30    68
Unnamed: 31     0
dtype: int64

In [15]:
df_clean = df.drop(columns=[
    "Unnamed: 27", "Unnamed: 28", "Unnamed: 29",
    "Unnamed: 30", "Unnamed: 31"
])

In [16]:
df_clean.shape

(517, 30)

In [17]:
df_clean.duplicated().sum()

np.int64(0)

In [18]:
df_clean.columns.tolist()

['ID',
 'UPA',
 'EventDate',
 'Employer',
 'Address1',
 'Address2',
 'city',
 'state',
 'Zip',
 'Latitude',
 'Longitude',
 'Primary_NAICS',
 'Hospitalized',
 'Amputation',
 'Loss_Of_Eye',
 'Inspection',
 'FinalNarrative',
 'Types_of_accidents',
 'Reason',
 'Nature',
 'NatureTitle',
 'Part_of_Body',
 'Part_of_Body_Title',
 'Event',
 'EventTitle',
 'Unnamed: 25',
 'Source',
 'sourceTitle',
 'Secondary_Source',
 'Secondary_Source_Title']

In [19]:
df_clean[['ID' , 'UPA']].duplicated().sum()

np.int64(0)

In [20]:
missing_counts = df_clean.isna().sum()
missing_counts[missing_counts > 0]

Address1                    1
Address2                  483
Latitude                    1
Longitude                   1
Inspection                420
Secondary_Source          192
Secondary_Source_Title    192
dtype: int64

In [21]:
df_clean["Inspection"].value_counts(dropna=False)

Inspection
NaN          420
1859347.0      1
1850754.0      1
1701616.0      1
1704287.0      1
            ...
1104205.0      1
1104650.0      1
1017786.0      1
1177789.0      1
1178824.0      1
Name: count, Length: 98, dtype: int64

In [22]:
df_clean["Inspection_Recorded"] = (
    df_clean["Inspection"].notna().astype(int)
)

In [23]:
df_clean.head(5)

,ID,UPA,EventDate,Employer,Address1,Address2,city,state,Zip,Latitude,...,Part_of_Body,Part_of_Body_Title,Event,EventTitle,Unnamed: 25,Source,sourceTitle,Secondary_Source,Secondary_Source_Title,Inspection_Recorded
0,20251111336,2365642,11/13/2025,Ruan Transportation Management Systems,Flowers Bakery,6000 NE Loop 410,SAN ANTONIO,TEXAS,78218,29.46,...,899,Multiple body parts n.e.c.,4142,Other fall to lower level 6 to 30 feet,"Falls, slips, trips",4741,"Vehicle trailers, trailing units",660,"Ground, travel, and support surfaces unspeci...",0
1,20251111151,2365320,11/10/2025,Wesco Distribution,5935 Eisenhauer Rd,Building 100,SAN ANTONIO,TEXAS,78218,29.50,...,53,Ankle(s),2723,"Collision with stationary object, nonroadway",Transportation incidents,8621,"Forklift, order picker, platform truck powered",6339,Structural barriers n.e.c.,1
2,20251111068,2370023,11/6/2025,Mata Trucking,FM 917,NaN,JOSHUA,TEXAS,76058,32.46,...,111,Brain,4142,Other fall to lower level 6 to 30 feet,"Falls, slips, trips",4741,"Vehicle trailers, trailing units",660,"Ground, travel, and support surfaces unspeci...",0
3,20251110889,2366721,11/1/2025,88 Trucking,12250 Lake June Rd Ste 110,NaN,BALCH SPRINGS,TEXAS,75180,32.73,...,520,Leg(s) unspecified,4141,Other fall to lower level less than 6 feet,"Falls, slips, trips",8432,"Straight trucks, box trucks",990,"Source, secondary source unspecified",0
4,20251010788,2365472,10/29/2025,Southeastern Freight Lines,9199 W. Hardy Road,NaN,HOUSTON,TEXAS,77022,29.84,...,441,"Hand(s), except finger(s)",6612,Injured by object pushed or pulled by person,Contact with objects and equipment,4749,Vehicle and machine attachments n.e.c.,4741,"Vehicle trailers, trailing units",0

In [24]:
df_clean.loc[
    df_clean[["Address1", "Latitude", "Longitude"]].isna().any(axis=1),["ID", "Employer", "Address1", "city", "Latitude", "Longitude"]]

,ID,Employer,Address1,city,Latitude,Longitude
64,2025087977,Proficient Auto Inc,I-20 & Cooper Street,ARLINGTON,NaN,NaN
466,2015107548,Southeastern Freight Lines,NaN,VICTORIA,28.8,-96.98

In [25]:
df_clean.loc[
    [64, 466],
    ["ID", "Employer", "Address1","Address2", "city", "Latitude", "Longitude"]
]

,ID,Employer,Address1,Address2,city,Latitude,Longitude
64,2025087977,Proficient Auto Inc,I-20 & Cooper Street,NaN,ARLINGTON,NaN,NaN
466,2015107548,Southeastern Freight Lines,NaN,NaN,VICTORIA,28.8,-96.98

In [26]:
df_clean.loc[64, "Latitude"] = 32.68
df_clean.loc[64, "Longitude"] = -97.12

In [27]:
df_clean.loc[466, "Address1"] = '1344 S Moody St'

In [28]:
df_clean.loc[
    [64, 466],
    ["ID", "Employer", "Address1","Address2", "city", "Latitude", "Longitude"]
]

,ID,Employer,Address1,Address2,city,Latitude,Longitude
64,2025087977,Proficient Auto Inc,I-20 & Cooper Street,NaN,ARLINGTON,32.68,-97.12
466,2015107548,Southeastern Freight Lines,1344 S Moody St,NaN,VICTORIA,28.80,-96.98

In [29]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      517 non-null    int64
 1   UPA                     517 non-null    int64
 2   EventDate               517 non-null    str
 3   Employer                517 non-null    str
 4   Address1                517 non-null    str
 5   Address2                34 non-null     str
 6   city                    517 non-null    str
 7   state                   517 non-null    str
 8   Zip                     517 non-null    int64
 9   Latitude                517 non-null    float64
 10  Longitude               517 non-null    float64
 11  Primary_NAICS           517 non-null    int64
 12  Hospitalized            517 non-null    int64
 13  Amputation              517 non-null    int64
 14  Loss_Of_Eye             517 non-null    int64
 15  Inspection              97 non-null     float64
 16  FinalNarrative          517 non-null    str
 17  Types_of_accidents      517 non-null    str
 18  Reason                  517 non-null    str
 19  Nature                  517 non-null    str
 20  NatureTitle             517 non-null    str
 21  Part_of_Body            517 non-null    str
 22  Part_of_Body_Title      517 non-null    str
 23  Event                   517 non-null    str
 24  EventTitle              517 non-null    str
 25  Unnamed: 25             517 non-null    str
 26  Source                  517 non-null    str
 27  sourceTitle             517 non-null    str
 28  Secondary_Source        325 non-null    str
 29  Secondary_Source_Title  325 non-null    str
 30  Inspection_Recorded     517 non-null    int64
dtypes: float64(3), int64(8), str(20)
memory usage: 380.0 KB

In [30]:
df_clean["EventDate"] = pd.to_datetime(
    df_clean["EventDate"],
    format="%m/%d/%Y"
)

In [31]:
df_clean['EventDate'].info()

<class 'pandas.Series'>
RangeIndex: 517 entries, 0 to 516
Series name: EventDate
Non-Null Count  Dtype
--------------  -----
517 non-null    datetime64[us]
dtypes: datetime64[us](1)
memory usage: 4.2 KB

In [32]:
df_clean["ID"] = (
    df_clean["ID"].astype(str)
)

In [33]:
df_clean["UPA"] = (
    df_clean["UPA"].astype(str)
)

In [34]:
df_clean["Zip"] = (
    df_clean["Zip"].astype(str)
)

In [35]:
df_clean["Primary_NAICS"] = (
    df_clean["Primary_NAICS"].astype(str)
)

In [36]:
df_clean["Inspection"] = df_clean["Inspection"].astype("Int64")

In [37]:
df_clean["Inspection"].dtype

Int64Dtype()

In [38]:
for col in ["Hospitalized", "Amputation", "Loss_Of_Eye", "Inspection_Recorded"]:
    print(col, df_clean[col].unique())

Hospitalized [1 0 2]
Amputation [0 1]
Loss_Of_Eye [0]
Inspection_Recorded [0 1]

In [39]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      517 non-null    str
 1   UPA                     517 non-null    str
 2   EventDate               517 non-null    datetime64[us]
 3   Employer                517 non-null    str
 4   Address1                517 non-null    str
 5   Address2                34 non-null     str
 6   city                    517 non-null    str
 7   state                   517 non-null    str
 8   Zip                     517 non-null    str
 9   Latitude                517 non-null    float64
 10  Longitude               517 non-null    float64
 11  Primary_NAICS           517 non-null    str
 12  Hospitalized            517 non-null    int64
 13  Amputation              517 non-null    int64
 14  Loss_Of_Eye             517 non-null    int64
 15  Inspection              97 non-null     Int64
 16  FinalNarrative          517 non-null    str
 17  Types_of_accidents      517 non-null    str
 18  Reason                  517 non-null    str
 19  Nature                  517 non-null    str
 20  NatureTitle             517 non-null    str
 21  Part_of_Body            517 non-null    str
 22  Part_of_Body_Title      517 non-null    str
 23  Event                   517 non-null    str
 24  EventTitle              517 non-null    str
 25  Unnamed: 25             517 non-null    str
 26  Source                  517 non-null    str
 27  sourceTitle             517 non-null    str
 28  Secondary_Source        325 non-null    str
 29  Secondary_Source_Title  325 non-null    str
 30  Inspection_Recorded     517 non-null    int64
dtypes: Int64(1), datetime64[us](1), float64(2), int64(4), str(23)
memory usage: 390.1 KB

In [40]:
df_clean.columns.tolist()

['ID',
 'UPA',
 'EventDate',
 'Employer',
 'Address1',
 'Address2',
 'city',
 'state',
 'Zip',
 'Latitude',
 'Longitude',
 'Primary_NAICS',
 'Hospitalized',
 'Amputation',
 'Loss_Of_Eye',
 'Inspection',
 'FinalNarrative',
 'Types_of_accidents',
 'Reason',
 'Nature',
 'NatureTitle',
 'Part_of_Body',
 'Part_of_Body_Title',
 'Event',
 'EventTitle',
 'Unnamed: 25',
 'Source',
 'sourceTitle',
 'Secondary_Source',
 'Secondary_Source_Title',
 'Inspection_Recorded']

In [41]:
df_clean = df_clean.drop(columns=["Unnamed: 25"])

In [42]:
df_clean.columns[19:31].tolist()

['Nature',
 'NatureTitle',
 'Part_of_Body',
 'Part_of_Body_Title',
 'Event',
 'EventTitle',
 'Source',
 'sourceTitle',
 'Secondary_Source',
 'Secondary_Source_Title',
 'Inspection_Recorded']

In [43]:
for col in df_clean.columns:
    if df_clean[col].dtype == "str":
        df_clean[col] = df_clean[col].str.strip()

In [44]:
df_clean["Types_of_accidents"].value_counts()

Types_of_accidents
Contact with objects and equipment                   191
Falls, slips, trips                                  150
Transportation incidents                              90
Exposure to harmful substances or environments        62
Overexertion and bodily reaction                      11
Violence and other injuries by persons or animals      7
Fires and explosions                                   6
Name: count, dtype: int64

In [45]:
df_clean["Reason"].value_counts()

Reason
Inadequate safety procedures        216
Insufficient detail in narrative    114
Unsafe workplace layout              82
Poor hazard identification           62
Poor equipment maintenance           18
Inadequate safety training           13
Missing machine guards               10
Failure to correct known hazards      2
Name: count, dtype: int64

In [46]:
df_clean.loc[
    df_clean["Reason"] == "Insufficient detail in narrative",
    ["FinalNarrative", "Reason"]
].head(10)

,FinalNarrative,Reason
0,An employee was closing the tarp on an aluminu...,Insufficient detail in narrative
1,An employee was operating a standing powered i...,Insufficient detail in narrative
3,A delivery driver was using a hand truck to ca...,Insufficient detail in narrative
5,An employee was lowering a safe stack beam ins...,Insufficient detail in narrative
9,An employee had been loading packages into a v...,Insufficient detail in narrative
10,An employee was exiting his semi-truck when he...,Insufficient detail in narrative
11,A driver was checking freight on a truck's lif...,Insufficient detail in narrative
16,An employee was on a step ladder loading produ...,Insufficient detail in narrative
21,An employee was moving a wooden crate by hand ...,Insufficient detail in narrative
24,An employee suffered burns to his right upper ...,Insufficient detail in narrative

In [47]:
df_clean.shape, df_clean.duplicated().sum()

((517, 30), np.int64(0))

In [48]:
missing = df_clean.isna().sum()
missing[missing > 0]

Address2                  483
Inspection                420
Secondary_Source          192
Secondary_Source_Title    192
dtype: int64

In [49]:
missing_percent = (
    df_clean.isna().sum() / len(df_clean) * 100
).round(1)

missing_percent[missing_percent > 0]

Address2                  93.4
Inspection                81.2
Secondary_Source          37.1
Secondary_Source_Title    37.1
dtype: float64

In [50]:
df_clean.head(5)

,ID,UPA,EventDate,Employer,Address1,Address2,city,state,Zip,Latitude,...,NatureTitle,Part_of_Body,Part_of_Body_Title,Event,EventTitle,Source,sourceTitle,Secondary_Source,Secondary_Source_Title,Inspection_Recorded
0,20251111336,2365642,2025-11-13,Ruan Transportation Management Systems,Flowers Bakery,6000 NE Loop 410,SAN ANTONIO,TEXAS,78218,29.46,...,Fractures,899,Multiple body parts n.e.c.,4142,Other fall to lower level 6 to 30 feet,4741,"Vehicle trailers, trailing units",660,"Ground, travel, and support surfaces unspecified",0
1,20251111151,2365320,2025-11-10,Wesco Distribution,5935 Eisenhauer Rd,Building 100,SAN ANTONIO,TEXAS,78218,29.50,...,Amputations involving bone loss,53,Ankle(s),2723,"Collision with stationary object, nonroadway",8621,"Forklift, order picker, platform truck powered",6339,Structural barriers n.e.c.,1
2,20251111068,2370023,2025-11-06,Mata Trucking,FM 917,NaN,JOSHUA,TEXAS,76058,32.46,...,Concussions,111,Brain,4142,Other fall to lower level 6 to 30 feet,4741,"Vehicle trailers, trailing units",660,"Ground, travel, and support surfaces unspecified",0
3,20251110889,2366721,2025-11-01,88 Trucking,12250 Lake June Rd Ste 110,NaN,BALCH SPRINGS,TEXAS,75180,32.73,...,Fractures,520,Leg(s) unspecified,4141,Other fall to lower level less than 6 feet,8432,"Straight trucks, box trucks",990,"Source, secondary source unspecified",0
4,20251010788,2365472,2025-10-29,Southeastern Freight Lines,9199 W. Hardy Road,NaN,HOUSTON,TEXAS,77022,29.84,...,"Cuts, lacerations, punctures without injury to...",441,"Hand(s), except finger(s)",6612,Injured by object pushed or pulled by person,4749,Vehicle and machine attachments n.e.c.,4741,"Vehicle trailers, trailing units",0

In [51]:
print(df_clean["city"].str.isupper().all())
print(df_clean["state"].str.isupper().all())

True
True

In [52]:
df_clean.to_csv("logistics_cleaned.csv", index=False)